version: '3.8'

services:
  postgres:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - 127.0.0.1:5499:5432